### PR TITLE
ITD calculation / HRIR low-frequency extension

### PR DESCRIPTION
**Pull request by davircarvalho**
# Interaural Time Difference (ITD):
- Added functions: ```SOFAgetITD()```,
- Modified/added functionality:  ```SOFAplotHRTF()```.

## ITD estimate for the SimpleFreeFieldHRIR conventions:

- Calculations via the threshold method (threshold value is a user-defined parameter);
- Output either in seconds or samples;
- Output in seconds can be determined by upsampling the HRIRs before onset calculation (upsample value is a user-defined parameter);
- Delays are also stored in ```Obj.Data.Delay```.

## ITD visualization:
- Added new type ```'ITDhorizontal'``` for the function ```SOFAplotHRTF()```, which generates a polar plot of the ITD at the horizontal plane;

# Low-frequency extension (LFE)
- Added functions: ```SOFAlfe()```.

## LFE for the SimpleFreeFieldHRIR conventions:
- Extrapolates the low-frequency content of  SOFA SimpleFreeFieldHRIR objects by considering a linear behavior to the low-frequency content.
- The start and end of the linear part of the HRTFs is a user-defined parameter.

# Demos
- Added functions: ```demo_SOFAgetITD()``` and ```demo_SOFAlfe```.
--Show the use and output visualization obtained with the added/modified functions mentioned above.

### CODE REVIEW

**Comment by isfmiho** [comment]
Hi,
thanks for your contribution!!! Sorry that it took me so long to continue with SOFA, I plan to integrate everything during the next days:
- I will merge the ITD feature to the plot function (which has progressed in the meantime).
- I will add the LFE function (changing the name from "get" to "convert")
- I will add the calculate ITD feature from [here](https://amtoolbox.org/amt-1.0.0/doc/common/itdestimator_code.php) which supports more methos, and try to adapt your demo file.
Br, Miho

**Comment by isfmiho** [comment]
Hi Davi, I tried to run your demos "as they are" and it seems that your ITD demo has some issues with resampling (Win10, Matlab R2021b). Can you reproduce the errors on your machine?


```
>>demo_SOFAgetITD
Index in position 1 exceeds array bounds. Index must not exceed 4098.

Error in signal.internal.resample.uniformResample (line 126)
    yTmp2 = yTmp(indV,:);

Error in resample (line 198)
            signal.internal.resample.uniformResample(xIn, isDimValSet, Dim, dimIn, numericArgs{:});

Error in SOFAgetITD>resample_this (line 141)
            IR(k, l, :) = resample(X(k,l,:), p, q, lpFilt);

Error in SOFAgetITD>sofaResample (line 111)
IR = resample_this(Obj.Data.IR, Fs_sofa, Fs);

Error in SOFAgetITD (line 44)
    Obj_upsample = sofaResample(Obj, fs_up);

Error in demo_SOFAgetITD (line 20)
[itd_time, Obj_time] = SOFAgetITD(Obj, 'time', 'thr', 20);
```

**Comment by isfmiho** [comment]
Hi Davi, the migration should be done; thanks a lot for the contribution!! And thanks for fixing the resample issue so quickly.
If you want you can have a look at the master branch. If you are happy we can close the pull request.

**Comment by davircarvalho** [comment]
I'm glad to contribute, thanks Miho!

**Pull request closed without merging**
